export default {
    // Authentication Errors
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
    INVALID_TOKEN: "INVALID_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    MISSING_TOKEN: "MISSING_TOKEN",
    BLACKLISTED_TOKEN: "BLACKLISTED_TOKEN",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",

    // Registration / Signup Errors
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
    WEAK_PASSWORD: "WEAK_PASSWORD",
    PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",
    INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
    VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",

    // User Errors
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
    ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
    ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",

    // Refresh & Session Errors
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    EXPIRED_REFRESH_TOKEN: "EXPIRED_REFRESH_TOKEN",
    SESSION_EXPIRED: "SESSION_EXPIRED",

    // System / Misc Errors
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    FILE_ID_NOT_FOUND: "FILE_ID_NOT_FOUND",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
