export default {
    // Authentication Errors
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    MISSING_TOKEN: "MISSING_TOKEN",
    BLACKLISTED_TOKEN: "BLACKLISTED_TOKEN",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

    // User Errors
    USER_NOT_FOUND: "USER_NOT_FOUND",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

    // System / Misc Errors
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    FILE_ID_NOT_FOUND: "FILE_ID_NOT_FOUND",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
