export default {
    // Authentication Errors
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    MISSING_TOKEN: "MISSING_TOKEN",
    BLACKLISTED_TOKEN: "BLACKLISTED_TOKEN",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
    NOT_FOUND: "NOT_FOUND",

    // User Errors
    USER_NOT_FOUND: "USER_NOT_FOUND",
    ITEM_NOT_FOUND: "ITEM_NOT_FOUND",

    // Cart errors
    EMPTY_CART: "EMPTY_CART",
    INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

    // Order errors
    ORDER_CANCELLATION_NOT_ALLOWED: "ORDER_CANCELLATION_NOT_ALLOWED",
    ORDER_ADDRESS_UPDATE_NOT_ALLOWED: "ORDER_ADDRESS_UPDATE_NOT_ALLOWED",
    NO_VALID_ADDRESS_FIELDS: "NO_VALID_ADDRESS_FIELDS",
    ORDER_STATUS_UPDATE_FAILD: "ORDER_STATUS_UPDATE_FAILD",

    // System / Misc Errors
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    FILE_ID_NOT_FOUND: "FILE_ID_NOT_FOUND",
    IMAGE_REQUIRED: "IMAGE_REQUIRED",
    IMAGE_NOT_FOUND: "IMAGE_NOT_FOUND",
    IMAGE_LIMIT_EXCEEDED: "IMAGE_LIMIT_EXCEEDED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
