export default {
    // Authentication Errors
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    MISSING_TOKEN: "MISSING_TOKEN",
    BLACKLISTED_TOKEN: "BLACKLISTED_TOKEN",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
    NOT_FOUND: "NOT_FOUND",

    // Payment Errors
    PAYMENT_CREATION_FAILED: "PAYMENT_CREATION_FAILED",
    INVALID_SIGNATURE: "INVALID_SIGNATURE",

    // System / Misc Errors
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
